Repository amm33/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#12 playwright test - shows if privacy policy exists
  tests/mywebclass_privacy.spec.js
Labels: Website Legal

#16 Link on pop up
  tests/mywebclass_linkOnPopUp.spec.js
  tests/mywebclass_popUp.spec.js
Labels: Website Legal

#17 Added more tests -> see if Privacy Policy is on the popup
  tests/mywebclass_linkOnPopUp.spec.js
  tests/mywebclass_wordsOnPopup.spec.js
Labels: Website Legal

#18 popup playwright test
  src/js/main.js
  tests/mywebclass_cookiesPopup.spec.js
Labels: Website Legal

#19 Added a playwright test that checks if cookies are being used
  tests/mywebclass_cookies.spec.js
Labels: Website Legal

#20 Popup buttons
  src/js/main.js
  tests/mywebclass_AgreeButton.spec.js
  tests/mywebclass_DisagreeButton.spec.js
Labels: Website Legal

#25 Seo
  src/privacy.html
  tests/mywebclass_SEOTesting.spec.js
  tests/mywebclass_measures.spec.js
  tests/mywebclass_performance.spec.js
Labels: SEO

#26 Aria attr test
  .github/workflows/playwright_video_lighthouse_report.yml
  package.json
  tests/mywebclass_ariaLabel.spec.js
  tests/mywebclass_navbar.spec.js
Labels: Web Accessibility and Internationalization

#27 Banner tests
  tests/mywebclass_banner.spec.js
  tests/mywebclass_bannerButton.spec.js
  tests/mywebclass_bannerImg.spec.js
Labels: Dev of Content Template and HomePage

#28 Img alt text test
  tests/mywebclass_imageAltText.spec.js
Labels: Web Accessibility and Internationalization

#31 Google analytics
  tests/mywebclass_googleAnalytics.spec.js
Labels: SEO

#37 changed some words
  src/js/main.js
Labels: enhancement, Dev of Content Template and HomePage

#38 Added some styling and changes to the banner
  src/assets/images/th.jpg
  src/index.html
Labels: enhancement, Dev of Content Template and HomePage

#39 Footer check
  .DS_Store
  tests/mywebclass_footerExists.spec.js
  tests/mywebclass_footerNotEmpty.spec.js
Labels: Web Accessibility and Internationalization

#40 Popup aria
  src/js/main.js
  tests/mywebclass_popupAriaModal.spec.js
Labels: Web Accessibility and Internationalization

#41 Privacy policy
  src/index.html
  src/privacy.html
Labels: Website Legal
